#include "texture_flags.hpp"

#include "bgfx/bgfx.h"

namespace tt {
	namespace texture_flags {
		/*
		 * Texture flags
		 */

		const uint64 TF_TEXTURE_NONE = BGFX_TEXTURE_NONE;
		const uint64 TF_TEXTURE_MSAA_SAMPLE = BGFX_TEXTURE_MSAA_SAMPLE;
		const uint64 TF_TEXTURE_RT = BGFX_TEXTURE_RT;
		const uint64 TF_TEXTURE_COMPUTE_WRITE = BGFX_TEXTURE_COMPUTE_WRITE;
		const uint64 TF_TEXTURE_SRGB = BGFX_TEXTURE_SRGB;
		const uint64 TF_TEXTURE_BLIT_DST = BGFX_TEXTURE_BLIT_DST;
		const uint64 TF_TEXTURE_READ_BACK = BGFX_TEXTURE_READ_BACK;

		const uint64 TF_TEXTURE_RT_MSAA_X2 = BGFX_TEXTURE_RT_MSAA_X2;
		const uint64 TF_TEXTURE_RT_MSAA_X4 = BGFX_TEXTURE_RT_MSAA_X4;
		const uint64 TF_TEXTURE_RT_MSAA_X8 = BGFX_TEXTURE_RT_MSAA_X8;
		const uint64 TF_TEXTURE_RT_MSAA_X16 = BGFX_TEXTURE_RT_MSAA_X16;
		const uint64 TF_TEXTURE_RT_WRITE_ONLY = BGFX_TEXTURE_RT_WRITE_ONLY;

		/*
		 * Sampler flags
		 */

		const uint64 TF_SAMPLER_U_MIRROR = BGFX_SAMPLER_U_MIRROR;
		const uint64 TF_SAMPLER_U_CLAMP = BGFX_SAMPLER_U_CLAMP;
		const uint64 TF_SAMPLER_U_BORDER = BGFX_SAMPLER_U_BORDER;

		const uint64 TF_SAMPLER_U_MASK = BGFX_SAMPLER_U_MASK;
		const uint64 TF_SAMPLER_V_MIRROR = BGFX_SAMPLER_V_MIRROR;
		const uint64 TF_SAMPLER_V_CLAMP = BGFX_SAMPLER_V_CLAMP;
		const uint64 TF_SAMPLER_V_BORDER = BGFX_SAMPLER_V_BORDER;

		const uint64 TF_SAMPLER_V_MASK = BGFX_SAMPLER_V_MASK;
		const uint64 TF_SAMPLER_W_MIRROR = BGFX_SAMPLER_W_MIRROR;
		const uint64 TF_SAMPLER_W_CLAMP = BGFX_SAMPLER_W_CLAMP;
		const uint64 TF_SAMPLER_W_BORDER = BGFX_SAMPLER_W_BORDER;

		const uint64 TF_SAMPLER_MIN_POINT = BGFX_SAMPLER_MIN_POINT;
		const uint64 TF_SAMPLER_MIN_ANISOTROPIC = BGFX_SAMPLER_MIN_ANISOTROPIC;

		const uint64 TF_SAMPLER_MAG_POINT = BGFX_SAMPLER_MAG_POINT;
		const uint64 TF_SAMPLER_MAG_ANISOTROPIC = BGFX_SAMPLER_MAG_ANISOTROPIC;

		const uint64 TF_SAMPLER_MAG_MASK = BGFX_SAMPLER_MAG_MASK;
		const uint64 TF_SAMPLER_MIP_POINT = BGFX_SAMPLER_MIP_POINT;

		const uint64 TF_SAMPLER_COMPARE_LESS = BGFX_SAMPLER_COMPARE_LESS;
		const uint64 TF_SAMPLER_COMPARE_LEQUAL = BGFX_SAMPLER_COMPARE_LEQUAL;
		const uint64 TF_SAMPLER_COMPARE_EQUAL = BGFX_SAMPLER_COMPARE_EQUAL;
		const uint64 TF_SAMPLER_COMPARE_GEQUAL = BGFX_SAMPLER_COMPARE_GEQUAL;
		const uint64 TF_SAMPLER_COMPARE_GREATER = BGFX_SAMPLER_COMPARE_GREATER;
		const uint64 TF_SAMPLER_COMPARE_NOTEQUAL = BGFX_SAMPLER_COMPARE_NOTEQUAL;
		const uint64 TF_SAMPLER_COMPARE_NEVER = BGFX_SAMPLER_COMPARE_NEVER;
		const uint64 TF_SAMPLER_COMPARE_ALWAYS = BGFX_SAMPLER_COMPARE_ALWAYS;

		const uint64 TF_SAMPLER_COMPARE_MASK = BGFX_SAMPLER_COMPARE_MASK;
		const uint64 TF_SAMPLER_SAMPLE_STENCIL = BGFX_SAMPLER_SAMPLE_STENCIL;

		const uint64 TF_SAMPLER_NONE = BGFX_SAMPLER_NONE;

		const uint64 TF_SAMPLER_POINT = BGFX_SAMPLER_POINT;

		const uint64 TF_SAMPLER_UVW_MIRROR = BGFX_SAMPLER_UVW_MIRROR;

		const uint64 TF_SAMPLER_UVW_CLAMP = BGFX_SAMPLER_UVW_CLAMP;

		const uint64 TF_SAMPLER_UVW_BORDER = BGFX_SAMPLER_UVW_BORDER;
	}    // namespace texture_flags
}    // namespace tt
